react-bootstrap: fix TS1205 when isolatedModules is enabled
error TS1205: Re-exporting a type when 'isolatedModules' is enabled requires using 'export type'.

13 export { Props as SelectoroidControlProps };
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~